[project]
name = "manim-widget"
version = "0.1.6"
description = "Manim Widget: manim, truly interactive, without the hassle"
readme = "README.md"
authors = [
    { name = "Antonin P", email = "antonin.peronnet@telecom-paris.fr" }
]
requires-python = ">=3.11"
dependencies = [
    "anywidget>=0.9.21",
    "manim>=0.20.1",
    "marimo>=0.23.0",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.155.2",
    "jsonschema>=4.26.0",
    "marimo>=0.21.1",
    "playwright>=1.58.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.2",
    "pytest-playwright>=0.7.2",
    "ruff>=0.15.8",
]
