name: Bug report
description: Something isn't working correctly
labels: [bug]
body:
  - type: markdown
    attributes:
      value: <!-- Thanks for your interest in this project! 🎉 -->

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What did you expect, and what did you get instead? Try to share reproducible code.
    placeholder: |
      I tried to do X but Y happened.
      Here is how you can reproduce it:

      ```python
      ```
    validations:
      required: true


  - type: textarea
    id: scene_data
    attributes:
      label: scene_data output
      description: >
        Any information that can be useful to debug.
        1. The json output `your_widget.data`
        2. the version you're running
        
        Paste the full output of `your_widget.scene_data` below.
        The entire visual state is encoded in this JSON — do you notice something fishy?
        A missing element, wrong coordinates, an animation that vanishes?
      placeholder: |
        <details>
        ```json
        Replace by output of:
        import json; print(json.dumps(widget.data))
        ```

        ```
        Replace by output of:
        from importlib.metadata import version; print(version("manim-widget"))
        ```
        </details>

  - type: textarea
    id: extra
    attributes:
      label: Anything else?
